---
title: "Reeb Biostats final"
output:
  pdf_document: default
  html_document: default
---

```{r, results='hide', warning=FALSE, message=FALSE}
library(httr)
library(ggplot2)
library(tidyr)
library(knitr)
library(lme4)
library(lmerTest)
library(car)
library(dplyr)


options(contrasts = c("contr.sum", "contr.poly"))



### download indiv datasets of students
myfile = "https://raw.githubusercontent.com/rachreeb/Biostat_final/master/Aster_PGH_CC_complete.csv"
phenotesta = read.csv(myfile)

myfile2 = "https://raw.githubusercontent.com/rachreeb/Biostat_final/master/Aster_PGH_edt_alex.csv"
phenotestb = read.csv(myfile2)

myfile3 = "https://raw.githubusercontent.com/rachreeb/Biostat_final/master/Aster_PHG_EO_complete.csv"
phenotestc = read.csv(myfile3)



### full join student datasets
phenotest = phenotesta %>%
  full_join(phenotestb, by = c( "observer", "id", "observed_on", "user_id", "url", "image_url", "latitude", "longitude", "place_county_name", "place_state_name", "place_country_name", "scientific_name", "common_name", "taxon_family_name", "status", "Habitat_forest_open", "part_or_whole", "leaves", "flowers_or_buds", "open_flowers", "fruit", "ripe_fruit")) %>%
  full_join(phenotestc, by =c(  "observer", "id", "observed_on", "user_id", "url", "image_url", "latitude", "longitude", "place_county_name", "place_state_name", "place_country_name", "scientific_name", "common_name", "taxon_family_name", "status", "Habitat_forest_open", "part_or_whole", "leaves", "flowers_or_buds", "open_flowers", "fruit", "ripe_fruit"))


```



```{r, results='hide', , warning=FALSE}
## fixing two messed up urls

phenotest$url[phenotest$id == 8020080] = "https://www.inaturalist.org/observations/8020080
"

phenotest$url[phenotest$id == 6759011] = "https://www.inaturalist.org/observations/6759011
"
```



```{r, results='hide', , warning=FALSE}


## summarize by the number "distinct" identifiers for each observation (1 = all scorers agree, 2 = 2 scorers in agreement and 1 disagreement, 3 = no scorers in agreement)
phenotest2 = phenotest %>%
  group_by(id, observed_on, url, scientific_name) %>%
  summarise(agree_part_or_whole = n_distinct(part_or_whole), agree_leaves = n_distinct(leaves), agree_flowers_or_buds = n_distinct(flowers_or_buds),agree_open_flowers = n_distinct(open_flowers), agree_fruit = n_distinct(fruit), agree_ripe_fruit = n_distinct(ripe_fruit)) 

## needed previously to find observation duplicates
##phenotest2$id[duplicated(phenotest2$id)]


```




```{r, results='hide', , warning=FALSE}
## create a long-form dataset

phenotest2_long <- gather(phenotest2, phenophase, agreement, agree_part_or_whole:agree_ripe_fruit, factor_key=TRUE)

## PROBELM: how do I filter "obvious no" observations out of the late phenology stages? (ie only some proportion of observations could be flowering, conditional on the presence of leaves)




```





## prelim data analysis 
```{r, , results='hide', warning=FALSE, message=FALSE}
library(car)

phenotest2_long$agreement = as.numeric(phenotest2_long$agreement)


## type 3 anova test for unbalanced data
### NOT normally distributed - right skew 
anovatest = aov(agreement ~ phenophase * scientific_name, data = phenotest2_long)
Anova(anovatest, type = 3)
# TukeyHSD(anovatest)

# both independently significant
kruskaltest_pheno = kruskal.test(agreement ~ phenophase, data = phenotest2_long)
kruskaltest_pheno


kruskaltest_species = kruskal.test(agreement ~ scientific_name, data = phenotest2_long)
kruskaltest_species

```







```{r, , results='hide', warning=FALSE, message=FALSE}
## Centering data by species?

phenotest2_long_sp = phenotest2_long %>%
  group_by(scientific_name, phenophase) %>%
  summarise(meanagree = mean(agreement))

aovtest = aov(meanagree ~ phenophase, data = phenotest2_long_sp)
anova(aovtest)
TukeyHSD(aovtest)
### after centering, only part or whole category is unique



```


## boxplot for data centered by species
```{r}
theme_set(theme_classic())

ggplot(data = phenotest2_long_sp, aes(x = phenophase, y = meanagree)) + geom_boxplot() + scale_fill_brewer(palette = "RdPu")


```

## making new binomial dataset
```{r}
phenotest2_long$agreement = as.numeric(phenotest2_long$agreement)

attach(phenotest2_long)

phenotest2_long$disagree_binary[phenotest2_long$agreement >= 2] = 1
phenotest2_long$disagree_binary[phenotest2_long$agreement <= 1] = 0

detach(phenotest2_long)


```

# --------FINAL--------



# final logistic regression test:

```{r}
logtest = glm(disagree_binary ~ phenophase + scientific_name, data = phenotest2_long, family = binomial(link="logit"))
capture.output(summary(logtest), file = "logmodel.txt")

anova_logtest = anova(logtest, test = "Chisq")


### anova comparing this model to a null model finds that phenophase and species were significantly different
capture.output(anova_logtest,file="nulltest.txt")



```



## final frequency table of binary agreements
```{r}
table_pheno = phenotest2_long %>%
  dplyr::group_by(phenophase, disagree_binary) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(freq = n / sum(n))
table_pheno

table_pheno2 = phenotest2_long %>%
  dplyr::group_by(scientific_name, disagree_binary) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(freq = n / sum(n))
table_pheno2

table_pheno3 = phenotest2_long %>%
  dplyr::group_by(disagree_binary) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(freq = n / sum(n))
table_pheno3
```

# Final Figure

### calculating means for each group
```{r}
meangroup = phenotest2_long %>%
  dplyr::group_by(scientific_name, phenophase) %>%
  dplyr::summarise(meanagree = mean(disagree_binary))

```


```{r}


theme_set(theme_classic())

jpeg("heatmap.jpeg")

ggplot(meangroup, aes(phenophase, scientific_name, fill = meanagree)) + geom_tile(color = "white") +
  scale_fill_gradient(limits = c(0,1), low="#feebe2", high="#c51b8a") + labs(fill = "Mean Disagreement") + xlab ( "Phenology Category") + ylab ("Species") + theme(
           axis.text.x  = element_text(angle=90, vjust=0.5, size=12)) + scale_x_discrete(labels = c("Whole Image?", "Leaves?", "Flowers?", "Open flowers?", "Fruits?", "Ripe Fruit?"))


dev.off()



```


